### ISSUE TITLE
Failing job causes panic

### ISSUE THREAD

**Issue by johnhofman** [Eneco/kronjob#14]
Scheduling a job that repeatedly fails eventually causes kronjob to panic:

```bash
[2017-06-07T14:04:39Z]  INFO This is Kronjob v0.1.7 commit=aa3b2f97b9a7f8991573e6ef196bb24bae6029ca tag=0.1.7
...
[2017-06-08T07:03:33Z]  INFO Job execution failed failed=1 job=job
panic: interface conversion: runtime.Object is nil, not *v1.Job

goroutine 221720 [running]:
panic(0x13324e0, 0xc42036f4c0)
	/home/travis/.gimme/versions/go1.7.5.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/eneco/kronjob/pkg/kronjob.(*Scheduler).HandleJobEvent(0xc42011b4f0, 0xc420cc5ec0, 0xc420280370)
	/home/travis/gopath/src/github.com/eneco/kronjob/pkg/kronjob/scheduler.go:302 +0x9d7
github.com/eneco/kronjob/pkg/kronjob.(*Scheduler).MonitorJob.func1(0xc420280370, 0xc42011b4f0, 0x1c806e0, 0xc420256de0)
	/home/travis/gopath/src/github.com/eneco/kronjob/pkg/kronjob/scheduler.go:262 +0x2c2
created by github.com/eneco/kronjob/pkg/kronjob.(*Scheduler).MonitorJob
	/home/travis/gopath/src/github.com/eneco/kronjob/pkg/kronjob/scheduler.go:265 +0x21a
```

**Comment by startopscollab** [comment]
I can confirm this issue except it happens to me even on sucesfull job run

[2017-09-12T08:05:34Z]  INFO Stop tailing pods for job... job=kronjob-stats-843730034-z80dk-job-1505203530
[2017-09-12T08:05:34Z]  INFO Retrieving pods for job... job=kronjob-stats-843730034-z80dk-job-1505203530
[2017-09-12T08:05:34Z]  INFO Deleting pod... pod=kronjob-stats-843730034-z80dk-job-1505203530-427tm
[2017-09-12T08:05:34Z]  INFO Job successfully cleaned up job=kronjob-stats-843730034-z80dk-job-1505203530
[2017-09-12T08:05:34Z]  INFO Completed job... job=kronjob-stats-843730034-z80dk-job-1505203530
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x4a9ffa]

goroutine 43 [running]:
panic(0x1328720, 0xc420014020)
	/home/travis/.gimme/versions/go1.7.5.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/eneco/kronjob/pkg/kronjob.(*Scheduler).HandleJobEvent(0xc42008b310, 0xc4204cdea0, 0xc42008a2d0)
	/home/travis/gopath/src/github.com/eneco/kronjob/pkg/kronjob/scheduler.go:313 +0x2ca
github.com/eneco/kronjob/pkg/kronjob.(*Scheduler).MonitorJob.func1(0xc42008a2d0, 0xc42008b310, 0x1c806e0, 0xc4201b6ed0)
	/home/travis/gopath/src/github.com/eneco/kronjob/pkg/kronjob/scheduler.go:262 +0x2c2
created by github.com/eneco/kronjob/pkg/kronjob.(*Scheduler).MonitorJob
	/home/travis/gopath/src/github.com/eneco/kronjob/pkg/kronjob/scheduler.go:265 +0x21a

**Comment by mozinator** [comment]
confirm, got the same problem
